trigger:
  branches:
  - master
  paths:
    include:
    - RestModels.EntityFramework/*
    exclude:
    - RestModels/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET Build'
  inputs:
    command: 'build'
    projects: 'RestModels/RestModels.EntityFramework.csproj'

- task: DotNetCoreCLI@2
  displayName: '.NET Pack'
  inputs:
    command: 'pack'
    packagesToPack: 'RestModels/RestModels.EntityFramework.csproj'
    nobuild: true
   
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet Push'
  inputs:
    command: push
    publishVstsFeed: 'RestModels/RestModels'
    allowPackageConflicts: true
